# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gts7-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts7 gts7l gts7lxxx gts7lwifi gts7xlwifi gts7xl gts7xlwifixx gts7xlxxx ,$(TARGET_DEVICE)),)

endif
