# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gts7-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts7,gts7lwifi,gts7lxx,gts7lxxx,gts7xl,gts7xlwifi,gts7xlxx,gts7xlxxx,$(TARGET_DEVICE)),)

endif
